# Site settings
title: Arusantimo Blog
email: ziziana0507@naver.com
description: null
baseurl: ''  
url: https://arusantimo.github.io/
twitter_username: null
github_username:  arusnatimo

# Build settings
markdown: kramdown
highlighter: pygments

# Pagination
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"

exclude: ["README.md"]

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
#   poetry:
#     output: true
#     permalink: /poetry/:path/


